//! Compatibility v1 codegen path for the `generate_rust` wrapper.
//!
//! New code should call `crate::generate` with a `ContextBuilder`.

use cambium_core::{Context, LeafType, Result, SchemaNode, SchemaNodeKind, SchemaTree};

pub(crate) fn generate_rust(ctx: &Context, module: &str) -> Result<String> {
    let tree = ctx.schema_tree(module)?;
    let mut emitter = RustEmitter::new(&tree, module);
    emitter.emit();
    Ok(emitter.output)
}

struct RustEmitter<'a> {
    tree: &'a SchemaTree,
    module: String,
    module_pascal: String,
    output: String,
}

impl<'a> RustEmitter<'a> {
    fn new(tree: &'a SchemaTree, module: &str) -> Self {
        Self {
            tree,
            module: module.to_string(),
            module_pascal: to_pascal_case(module),
            output: String::new(),
        }
    }

    fn emit(&mut self) {
        self.push(&format!(
            "// Generated by cambium-codegen for module {:?}.\n// Do not edit by hand.\n",
            self.module
        ));

        // Shared XML text-escaping helper used by every generated serializer.
        self.push(
            "fn cambium_xml_escape_text(s: &str) -> String {\n\
             \tlet mut out = String::with_capacity(s.len());\n\
             \tfor c in s.chars() {\n\
             \t\tmatch c {\n\
             \t\t\t'&' => out.push_str(\"&amp;\"),\n\
             \t\t\t'<' => out.push_str(\"&lt;\"),\n\
             \t\t\t'>' => out.push_str(\"&gt;\"),\n\
             \t\t\t_ => out.push(c),\n\
             \t\t}\n\
             \t}\n\
             \tout\n}\n\n",
        );

        let root = self.tree.root();
        for child in root.children() {
            self.emit_node_struct(child, &self.module_pascal.clone());
        }

        // Emit a synthetic module struct that owns the top-level nodes.
        self.push(&format!("pub struct {} {{", self.module_pascal));
        for child in root.children() {
            if is_emitted_kind(child.kind()) {
                let ty = root_field_type(&self.module_pascal, child);
                self.push(&format!("\tpub {}: {},", child.name(), ty));
            }
        }
        self.push("}\n");

        self.push(&format!(
            "impl {} {{\n\tpub const MODULE_NS: &str = {:?};\n",
            self.module_pascal,
            self.tree.module_ns()
        ));
        self.push("\tpub fn to_xml(&self) -> String {");
        self.push("\t\tlet mut s = String::new();");
        for child in root.children() {
            if !is_emitted_kind(child.kind()) {
                continue;
            }
            let ns = self.tree.module_ns();
            let ns_attr = if ns.is_empty() {
                String::new()
            } else {
                format!(" xmlns=\\\"{}\\\"", ns)
            };
            match child.kind() {
                SchemaNodeKind::Container => {
                    self.push(&format!(
                        "\t\ts.push_str(\"<{}{}>\\n\");",
                        child.name(),
                        ns_attr
                    ));
                    self.push(&format!("\t\tself.{}.write_xml(&mut s, 1);", child.name()));
                    self.push(&format!("\t\ts.push_str(\"</{}>\\n\");", child.name()));
                }
                SchemaNodeKind::List => {
                    self.push(&format!("\t\tfor entry in &self.{} {{", child.name()));
                    self.push(&format!(
                        "\t\t\ts.push_str(\"<{}{}>\\n\");",
                        child.name(),
                        ns_attr
                    ));
                    self.push("\t\t\tentry.write_xml(&mut s, 1);");
                    self.push(&format!("\t\t\ts.push_str(\"</{}>\\n\");", child.name()));
                    self.push("\t\t}");
                }
                _ => {}
            }
        }
        self.push("\t\ts");
        self.push("\t}\n}\n");
    }

    fn emit_node_struct(&mut self, node: &SchemaNode, prefix: &str) {
        if !is_struct_kind(node.kind()) {
            return;
        }

        let is_list = node.kind() == SchemaNodeKind::List;
        let base_name = child_type_name(prefix, node);
        let struct_name = if is_list {
            entry_type_name_from_base(&base_name)
        } else {
            base_name.clone()
        };

        let ordered = ordered_children(node);

        self.push("#[derive(Debug, Clone, Default, PartialEq, Eq)]");
        self.push(&format!("pub struct {} {{", struct_name));
        for child in &ordered {
            let field_type = child_field_type(&struct_name, child);
            self.push(&format!("\tpub {}: {},", child.name(), field_type));
        }
        self.push("}\n");

        // Field-order manifest: the exact declaration order from the schema,
        // with list keys moved to the front.
        let fields: Vec<_> = ordered.iter().map(|c| format!("{:?}", c.name())).collect();
        self.push(&format!(
            "impl {} {{\n\tpub const FIELD_ORDER: &[&str] = &[{}];",
            struct_name,
            fields.join(", ")
        ));

        // Serializer that walks the manifest order.
        self.push("\n\tpub fn write_xml(&self, w: &mut String, depth: usize) {");
        self.push("\t\tlet indent = \" \".repeat(depth * 2);");
        for child in &ordered {
            self.emit_child_serialization(child, &struct_name);
        }
        self.push("\t}\n}\n");

        // Recurse into nested containers and list entry structs.
        for child in node.children() {
            if is_struct_kind(child.kind()) {
                self.emit_node_struct(child, &struct_name);
            }
        }
    }

    fn emit_child_serialization(&mut self, child: &SchemaNode, _struct_name: &str) {
        match child.kind() {
            SchemaNodeKind::Leaf => {
                self.push(&format!(
                    "\t\tw.push_str(&format!(\"{{}}<{}>{{}}</{}>\\n\", &indent, cambium_xml_escape_text(&self.{}.to_string())));",
                    child.name(),
                    child.name(),
                    child.name()
                ));
            }
            SchemaNodeKind::LeafList => {
                self.push(&format!("\t\tfor v in &self.{} {{", child.name()));
                self.push(&format!(
                    "\t\t\tw.push_str(&format!(\"{{}}<{}>{{}}</{}>\\n\", &indent, cambium_xml_escape_text(&v.to_string())));",
                    child.name(),
                    child.name()
                ));
                self.push("\t\t}");
            }
            SchemaNodeKind::Container => {
                self.push(&format!(
                    "\t\tw.push_str(&format!(\"{{}}<{}>\\n\", &indent));",
                    child.name()
                ));
                self.push(&format!(
                    "\t\tself.{}.write_xml(w, depth + 1);",
                    child.name()
                ));
                self.push(&format!(
                    "\t\tw.push_str(&format!(\"{{}}</{}>\\n\", &indent));",
                    child.name()
                ));
            }
            SchemaNodeKind::List => {
                self.push(&format!("\t\tfor entry in &self.{} {{", child.name()));
                self.push(&format!(
                    "\t\t\tw.push_str(&format!(\"{{}}<{}>\\n\", &indent));",
                    child.name()
                ));
                self.push("\t\t\tentry.write_xml(w, depth + 1);");
                self.push(&format!(
                    "\t\t\tw.push_str(&format!(\"{{}}</{}>\\n\", &indent));",
                    child.name()
                ));
                self.push("\t\t}");
            }
            _ => {}
        }
    }

    fn push(&mut self, line: &str) {
        self.output.push_str(line);
        self.output.push('\n');
    }
}

fn is_struct_kind(kind: SchemaNodeKind) -> bool {
    matches!(kind, SchemaNodeKind::Container | SchemaNodeKind::List)
}

fn is_emitted_kind(kind: SchemaNodeKind) -> bool {
    matches!(
        kind,
        SchemaNodeKind::Leaf
            | SchemaNodeKind::LeafList
            | SchemaNodeKind::Container
            | SchemaNodeKind::List
    )
}

fn child_type_name(prefix: &str, node: &SchemaNode) -> String {
    format!("{}{}", prefix, to_pascal_case(node.name()))
}

fn entry_type_name_from_base(base: &str) -> String {
    format!("{}Entry", base)
}

fn entry_type_name(prefix: &str, node: &SchemaNode) -> String {
    entry_type_name_from_base(&child_type_name(prefix, node))
}

fn leaf_rust_type(ty: LeafType) -> &'static str {
    match ty {
        LeafType::String | LeafType::Unknown => "String",
        LeafType::Int => "i64",
        LeafType::Bool => "bool",
        _ => "String",
    }
}

fn root_field_type(prefix: &str, node: &SchemaNode) -> String {
    match node.kind() {
        SchemaNodeKind::Container => child_type_name(prefix, node),
        SchemaNodeKind::List => format!("Vec<{}>", entry_type_name(prefix, node)),
        SchemaNodeKind::Leaf => leaf_rust_type(node.leaf_type()).to_string(),
        SchemaNodeKind::LeafList => format!("Vec<{}>", leaf_rust_type(node.leaf_type())),
        _ => "String".to_string(),
    }
}

fn child_field_type(prefix: &str, node: &SchemaNode) -> String {
    root_field_type(prefix, node)
}

/// Return children in the order they should appear in generated code and XML.
///
/// For a list, key leaves are moved to the front in key-statement order; the
/// remaining emitted children keep their schema declaration order.
fn ordered_children(node: &SchemaNode) -> Vec<&SchemaNode> {
    let all: Vec<_> = node
        .children()
        .iter()
        .filter(|c| is_emitted_kind(c.kind()))
        .collect();
    if node.kind() != SchemaNodeKind::List {
        return all;
    }

    let mut keys = Vec::new();
    let mut others = Vec::new();
    let key_names: std::collections::HashSet<_> = node.key_names().iter().cloned().collect();
    for child in all {
        if key_names.contains(child.name()) || child.is_key() {
            keys.push(child);
        } else {
            others.push(child);
        }
    }

    // Preserve the key-statement order declared in the schema.
    let mut ordered_keys = Vec::new();
    for name in node.key_names() {
        if let Some(k) = keys.iter().find(|c| c.name() == name) {
            ordered_keys.push(*k);
        }
    }
    // Append any keys not named by key_names (defensive).
    for k in keys {
        if !ordered_keys.contains(&k) {
            ordered_keys.push(k);
        }
    }

    ordered_keys.extend(others);
    ordered_keys
}

fn to_pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for c in s.chars() {
        if c == '-' || c == '_' || c == '.' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    if out.is_empty() {
        out.push_str("Node");
    }
    out
}
