// Package codegen is the Go side of Cambium's YANG → typed-language generator.
//
// v2 consumes the rich goyang-grade Module/SchemaNodeRef API and emits typed
// structs with a per-struct field-order manifest plus self-contained native XML
// and JSON_IETF serializers. The generated walk follows the compiled YANG
// declaration order (list keys first), so output is byte-identical to libyang
// for the same data.
package codegen

import (
	"fmt"
	"go/format"
	"math/big"
	"sort"
	"strconv"
	"strings"

	"github.com/signalbreak-labs/cambium/go/cambium"
	"github.com/signalbreak-labs/cambium/go/internal/xsdregex"
)

// GenerateGo returns a deterministic, gofmt-stable Go source file for the
// implemented module named module.
func GenerateGo(ctx *cambium.Context, module string) (string, error) {
	mod, err := ctx.Schema(module)
	if err != nil {
		return "", err
	}
	gen := &goEmitter{
		module:       mod,
		moduleName:   mod.Name(),
		modulePascal: toPascalCase(mod.Name()),
		ns:           mod.Namespace(),
	}
	src := gen.emit()
	if gen.emitErr != nil {
		return "", gen.emitErr
	}
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return src, fmt.Errorf("generated source is not gofmt-clean: %w", err)
	}
	return string(formatted), nil
}

type goEmitter struct {
	module             cambium.Module
	moduleName         string
	modulePascal       string
	ns                 string
	helpers            map[string]bool
	typeSnippets       map[string]string
	intRangeTypes      map[string]intRangeInfo
	stringLengthTypes  map[string]stringLengthInfo
	emittedDecimal64   bool
	emittedUserOrdered bool
	enumTypes          map[string]bool
	bitsTypes          map[string]bool
	identityrefTypes   map[string]bool
	unionTypes         map[string]bool
	emittedInstanceID  bool
	needsSort          bool
	emittedAnyData     bool
	emittedMetadata    bool
	emitErr            error
}

type intRangeInfo struct {
	kind   cambium.IntKind
	bounds []cambium.RangeBound
}

type stringLengthInfo struct {
	bounds []cambium.RangeBound
}

// fieldInfo carries everything needed to emit one generated struct field and
// its serializers.
type fieldInfo struct {
	node          cambium.SchemaNodeRef
	ident         string // exported Go field identifier
	wire          string // YANG wire name
	moduleName    string // owner module for JSON_IETF namespace qualification
	namespace     string // owner XML namespace
	goType        string // Go type expression
	optional      bool   // true for optional leaves / presence containers
	jsonKind      string // "String" | "BareNumber" | "QuotedNumber" | "Bool" | "Empty" | "InstanceIdentifier"
	isNewtype     bool   // true for generated range/length/decimal64 wrapper types
	intSigned     bool   // true for signed integer native types
	isEnum        bool
	isBits        bool
	isIdentityref bool
	isUnion       bool
}

func (g *goEmitter) emit() string {
	g.helpers = make(map[string]bool)
	g.typeSnippets = make(map[string]string)
	g.intRangeTypes = make(map[string]intRangeInfo)
	g.stringLengthTypes = make(map[string]stringLengthInfo)
	g.enumTypes = make(map[string]bool)
	g.bitsTypes = make(map[string]bool)
	g.identityrefTypes = make(map[string]bool)
	g.unionTypes = make(map[string]bool)

	rootChildren := g.documentTopLevelChildren()

	var body strings.Builder
	rootFields := g.collectFields(g.modulePascal, rootChildren)
	for _, f := range rootFields {
		if isStructKind(f.node.Kind()) {
			g.emitStructRec(f.node, fieldConcreteType(f), &body)
		}
	}
	g.emitCambiumStructInterface(&body)
	g.emitRootStruct(rootFields, &body)
	g.emitOperationDocuments(&body)

	out := &strings.Builder{}
	fmt.Fprintf(out, "// Generated by cambium-codegen for module %q.\n// Do not edit by hand.\n\n", g.moduleName)
	out.WriteString("package generated\n\n")
	g.emitImports(out)
	g.emitHelpers(out)
	out.WriteString(body.String())
	return out.String()
}

func (g *goEmitter) documentTopLevelChildren() []cambium.SchemaNodeRef {
	children := g.orderedChildrenList(g.module.TopLevel())
	seen := map[string]bool{moduleIdentityKey(g.module): true}
	for _, imp := range g.module.Imports() {
		imported, ok := g.module.ResolvePrefix(imp.Prefix)
		if !ok {
			continue
		}
		key := moduleIdentityKey(imported)
		if seen[key] {
			continue
		}
		seen[key] = true
		children = append(children, g.orderedChildrenList(imported.TopLevel())...)
	}
	return children
}

func moduleIdentityKey(mod cambium.Module) string {
	revision, _ := mod.Revision()
	return mod.Name() + "\x00" + revision
}

func (g *goEmitter) emitImports(out *strings.Builder) {
	needStrings := true // strings.Builder, strings.Repeat
	needJSONParse := g.helpers["jsonParse"]
	needFmt := needJSONParse || g.helpers["xmlEscape"] || g.helpers["jsonEscape"] || g.helpers["binaryParse"] || g.helpers["patternValidate"] || len(g.intRangeTypes) > 0 || len(g.stringLengthTypes) > 0 || g.emittedDecimal64 || len(g.bitsTypes) > 0
	needStrconv := needJSONParse || g.helpers["strconv"] || len(g.intRangeTypes) > 0 || g.emittedDecimal64
	needMathBig := needJSONParse && g.emittedDecimal64
	needUTF8 := needJSONParse || len(g.stringLengthTypes) > 0

	imports := []string{}
	if needStrings {
		imports = append(imports, "\"strings\"")
	}
	if g.helpers["binaryParse"] {
		imports = append(imports, "\"encoding/base64\"")
	}
	if needJSONParse {
		imports = append(imports, "\"encoding/json\"")
		imports = append(imports, "\"io\"")
	}
	if needFmt {
		imports = append(imports, "\"fmt\"")
	}
	if g.helpers["patternValidate"] {
		imports = append(imports, "\"regexp\"")
	}
	if needMathBig {
		imports = append(imports, "\"math/big\"")
	}
	if needStrconv {
		imports = append(imports, "\"strconv\"")
	}
	if needUTF8 {
		imports = append(imports, "\"unicode/utf8\"")
	}
	if g.needsSort || g.helpers["jsonParse"] {
		imports = append(imports, "\"sort\"")
	}
	sort.Strings(imports)

	if len(imports) == 1 {
		fmt.Fprintf(out, "import %s\n\n", imports[0])
		return
	}
	out.WriteString("import (\n")
	for _, imp := range imports {
		fmt.Fprintf(out, "\t%s\n", imp)
	}
	out.WriteString(")\n\n")
}

func (g *goEmitter) emitHelpers(out *strings.Builder) {
	if g.helpers["jsonParse"] {
		g.emitJSONParseHelper(out)
	}
	if g.helpers["binaryParse"] {
		g.emitBinaryParseHelper(out)
	}
	if g.helpers["patternValidate"] {
		g.emitPatternValidateHelper(out)
	}
	if len(g.bitsTypes) > 0 {
		g.emitBitsParseHelper(out)
	}
	if g.helpers["xmlEscape"] {
		out.WriteString("// cambiumXMLEscapeText escapes &, <, and > for XML text content.\n")
		out.WriteString("func cambiumXMLEscapeText(s string) string {\n")
		out.WriteString("\treturn strings.NewReplacer(\"&\", \"&amp;\", \"<\", \"&lt;\", \">\", \"&gt;\").Replace(s)\n")
		out.WriteString("}\n\n")
		out.WriteString("// cambiumXMLEscapeAttr escapes text for a double-quoted XML attribute value.\n")
		out.WriteString("func cambiumXMLEscapeAttr(s string) string {\n")
		out.WriteString("\treturn strings.NewReplacer(\"&\", \"&amp;\", \"\\\"\", \"&quot;\", \"<\", \"&lt;\", \">\", \"&gt;\").Replace(s)\n")
		out.WriteString("}\n\n")
		out.WriteString("func cambiumValidateXMLPrefix(prefix string) error {\n")
		out.WriteString("\tif prefix == \"\" { return nil }\n")
		out.WriteString("\tif strings.EqualFold(prefix, \"xml\") || strings.EqualFold(prefix, \"xmlns\") {\n")
		out.WriteString("\t\treturn fmt.Errorf(\"invalid XML namespace prefix %q\", prefix)\n")
		out.WriteString("\t}\n")
		out.WriteString("\tfor i, r := range prefix {\n")
		out.WriteString("\t\tvalid := r == '_' || (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z')\n")
		out.WriteString("\t\tif i > 0 {\n")
		out.WriteString("\t\t\tvalid = valid || r == '-' || r == '.' || (r >= '0' && r <= '9')\n")
		out.WriteString("\t\t}\n")
		out.WriteString("\t\tif !valid { return fmt.Errorf(\"invalid XML namespace prefix %q\", prefix) }\n")
		out.WriteString("\t}\n")
		out.WriteString("\treturn nil\n")
		out.WriteString("}\n\n")
	}
	if g.helpers["jsonEscape"] {
		out.WriteString("// cambiumJSONEscape renders a string as a JSON string literal, including\n")
		out.WriteString("// the surrounding quotes. It matches libyang's json_print_string: named\n")
		out.WriteString("// escapes only for \", \\, \\r, and \\t; every other ASCII control is \\uXXXX\n")
		out.WriteString("// with uppercase hex; multi-byte UTF-8 passes through unchanged.\n")
		out.WriteString("func cambiumJSONEscape(s string) string {\n")
		out.WriteString("\tvar b strings.Builder\n")
		out.WriteString("\tb.WriteByte('\"')\n")
		out.WriteString("\tfor _, c := range s {\n")
		out.WriteString("\t\tswitch c {\n")
		out.WriteString("\t\tcase '\"':\n")
		out.WriteString("\t\t\tb.WriteString(`\\\"`)\n")
		out.WriteString("\t\tcase '\\\\':\n")
		out.WriteString("\t\t\tb.WriteString(`\\\\`)\n")
		out.WriteString("\t\tcase '\\r':\n")
		out.WriteString("\t\t\tb.WriteString(`\\r`)\n")
		out.WriteString("\t\tcase '\\t':\n")
		out.WriteString("\t\t\tb.WriteString(`\\t`)\n")
		out.WriteString("\t\tdefault:\n")
		out.WriteString("\t\t\tif c < 0x20 || c == 0x7f {\n")
		out.WriteString("\t\t\t\tb.WriteString(fmt.Sprintf(`\\u%04X`, c))\n")
		out.WriteString("\t\t\t} else {\n")
		out.WriteString("\t\t\t\tb.WriteRune(c)\n")
		out.WriteString("\t\t\t}\n")
		out.WriteString("\t\t}\n")
		out.WriteString("\t}\n")
		out.WriteString("\tb.WriteByte('\"')\n")
		out.WriteString("\treturn b.String()\n")
		out.WriteString("}\n\n")
	}
	if g.helpers["jsonIndent"] {
		out.WriteString("// cambiumJSONIndent writes a newline followed by depth two-space indents.\n")
		out.WriteString("func cambiumJSONIndent(b *strings.Builder, depth int) {\n")
		out.WriteString("\tb.WriteByte('\\n')\n")
		out.WriteString("\tfor i := 0; i < depth; i++ {\n")
		out.WriteString("\t\tb.WriteString(\"  \")\n")
		out.WriteString("\t}\n")
		out.WriteString("}\n\n")
	}
	if g.emittedDecimal64 {
		g.emitDecimal64Helper(out)
	}
	if g.emittedUserOrdered {
		g.emitUserOrderedVecHelper(out)
	}
	if g.emittedInstanceID {
		g.emitInstanceIdentifierHelper(out)
	}
	if g.emittedAnyData {
		g.emitAnyDataHelper(out)
	}
	if g.emittedMetadata {
		g.emitMetadataHelper(out)
	}
	typeKeys := make([]string, 0)
	for key := range g.typeSnippets {
		typeKeys = append(typeKeys, key)
	}
	sort.Strings(typeKeys)
	for _, key := range typeKeys {
		out.WriteString(g.typeSnippets[key])
	}
	intRangeKeys := make([]string, 0)
	for name := range g.intRangeTypes {
		intRangeKeys = append(intRangeKeys, name)
	}
	sort.Strings(intRangeKeys)
	for _, name := range intRangeKeys {
		g.emitIntRangeHelper(name, g.intRangeTypes[name], out)
	}
	stringLengthKeys := make([]string, 0)
	for name := range g.stringLengthTypes {
		stringLengthKeys = append(stringLengthKeys, name)
	}
	sort.Strings(stringLengthKeys)
	for _, name := range stringLengthKeys {
		g.emitStringLengthHelper(name, g.stringLengthTypes[name], out)
	}
}

func (g *goEmitter) emitBitsParseHelper(out *strings.Builder) {
	out.WriteString(tmplBitsParse)
}

func (g *goEmitter) emitBinaryParseHelper(out *strings.Builder) {
	out.WriteString(tmplBinaryParse)
}

func (g *goEmitter) emitDecimal64Helper(out *strings.Builder) {
	out.WriteString(tmplDecimal64)
}

func (g *goEmitter) emitUserOrderedVecHelper(out *strings.Builder) {
	out.WriteString(tmplUserOrderedVec)
}

func (g *goEmitter) emitInstanceIdentifierHelper(out *strings.Builder) {
	out.WriteString(tmplInstanceIdentifier)
}

func (g *goEmitter) emitAnyDataHelper(out *strings.Builder) {
	out.WriteString(tmplAnyData)
}

func (g *goEmitter) emitMetadataHelper(out *strings.Builder) {
	view := metadataView{}
	seenModules := make(map[string]bool)
	addBinding := func(mod cambium.Module) {
		name := mod.Name()
		if name == "" || seenModules[name] {
			return
		}
		seenModules[name] = true
		view.Bindings = append(view.Bindings, metadataBinding{Name: name, Prefix: mod.Prefix(), Namespace: mod.Namespace()})
	}
	addBinding(g.module)
	for _, imp := range g.module.Imports() {
		if imported, ok := g.module.ResolvePrefix(imp.Prefix); ok {
			addBinding(imported)
		}
	}
	annotations := g.metadataAnnotationNamesByModule()
	modules := make([]string, 0, len(annotations))
	for module := range annotations {
		modules = append(modules, module)
	}
	sort.Strings(modules)
	for _, module := range modules {
		view.Annotations = append(view.Annotations, metadataAnnotationGroup{Module: module, Locals: annotations[module]})
	}
	if err := tmplMetadata.Execute(out, view); err != nil {
		g.recordEmitError(err)
	}
}

func (g *goEmitter) metadataAnnotationNamesByModule() map[string][]string {
	annotations := make(map[string][]string)
	seenAnnotations := make(map[string]map[string]bool)
	addModule := func(mod cambium.Module) {
		moduleName := mod.Name()
		if moduleName == "" {
			return
		}
		for _, ext := range mod.Extensions() {
			if ext.ModuleName() != "ietf-yang-metadata" || ext.Name() != "annotation" {
				continue
			}
			name, ok := ext.Argument()
			if !ok || name == "" {
				continue
			}
			if seenAnnotations[moduleName] == nil {
				seenAnnotations[moduleName] = make(map[string]bool)
			}
			if seenAnnotations[moduleName][name] {
				continue
			}
			seenAnnotations[moduleName][name] = true
			annotations[moduleName] = append(annotations[moduleName], name)
		}
	}

	addModule(g.module)
	seenModules := map[string]bool{moduleIdentityKey(g.module): true}
	for _, imp := range g.module.Imports() {
		imported, ok := g.module.ResolvePrefix(imp.Prefix)
		if !ok {
			continue
		}
		key := moduleIdentityKey(imported)
		if seenModules[key] {
			continue
		}
		seenModules[key] = true
		addModule(imported)
	}
	for module := range annotations {
		sort.Strings(annotations[module])
	}
	return annotations
}

func (g *goEmitter) emitIntRangeHelper(name string, info intRangeInfo, out *strings.Builder) {
	goType := goTypeForIntKind(info.kind)
	limits := intTypeLimits(info.kind)
	bounds := info.bounds

	ranges := make([]string, 0, len(bounds))
	zeroInRange := false
	var minVal int64 = -1
	if len(bounds) == 0 {
		lo := parseIntBound("min", limits)
		hi := parseIntBound("max", limits)
		ranges = append(ranges, fmt.Sprintf("(v >= %d && v <= %d)", lo, hi))
		if lo <= 0 && 0 <= hi {
			zeroInRange = true
		}
		minVal = lo
	}
	for _, b := range bounds {
		lo := parseIntBound(b.Min(), limits)
		hi := parseIntBound(b.Max(), limits)
		ranges = append(ranges, fmt.Sprintf("(v >= %d && v <= %d)", lo, hi))
		if lo <= 0 && 0 <= hi {
			zeroInRange = true
		}
		if minVal == -1 || lo < minVal {
			minVal = lo
		}
	}
	check := strings.Join(ranges, " || ")
	defaultExpr := ""
	if !zeroInRange {
		defaultExpr = fmt.Sprintf("\n// Default%s returns a valid default value.\nfunc Default%s() %s {\n\tv, _ := New%s(%d)\n\treturn v\n}\n", name, name, name, name, minVal)
	}

	fmt.Fprintf(out, "// %s is a generated YANG integer range type.\n", name)
	fmt.Fprintf(out, "type %s struct {\n\tvalue %s\n}\n\n", name, goType)
	fmt.Fprintf(out, "// New%s creates a %s if v is within range.\n", name, name)
	fmt.Fprintf(out, "func New%s(v %s) (%s, error) {\n", name, goType, name)
	fmt.Fprintf(out, "\tif %s {\n", check)
	fmt.Fprintf(out, "\t\treturn %s{value: v}, nil\n", name)
	fmt.Fprintf(out, "\t}\n")
	fmt.Fprintf(out, "\treturn %s{}, fmt.Errorf(\"value %%d out of range for %s\", v)\n", name, name)
	fmt.Fprintf(out, "}\n\n")
	fmt.Fprintf(out, "// Get returns the wrapped value.\n")
	fmt.Fprintf(out, "func (r %s) Get() %s { return r.value }\n\n", name, goType)
	fmt.Fprintf(out, "// String returns the decimal representation.\n")
	if isSignedIntKind(info.kind) {
		fmt.Fprintf(out, "func (r %s) String() string { return strconv.FormatInt(int64(r.value), 10) }\n\n", name)
	} else {
		fmt.Fprintf(out, "func (r %s) String() string { return strconv.FormatUint(uint64(r.value), 10) }\n\n", name)
	}
	out.WriteString(defaultExpr)
}

func (g *goEmitter) emitStringLengthHelper(name string, info stringLengthInfo, out *strings.Builder) {
	bounds := info.bounds

	ranges := make([]string, 0, len(bounds))
	minLen := int64(-1)
	if len(bounds) == 0 {
		lo := parseLengthBound("min")
		hi := parseLengthBound("max")
		ranges = append(ranges, fmt.Sprintf("(l >= %d && l <= %d)", lo, hi))
		minLen = lo
	}
	for _, b := range bounds {
		lo := parseLengthBound(b.Min())
		hi := parseLengthBound(b.Max())
		ranges = append(ranges, fmt.Sprintf("(l >= %d && l <= %d)", lo, hi))
		if minLen == -1 || int64(lo) < minLen {
			minLen = int64(lo)
		}
	}
	check := strings.Join(ranges, " || ")
	defaultExpr := ""
	if minLen > 0 {
		defaultExpr = fmt.Sprintf("\n// Default%s returns a valid default value.\nfunc Default%s() %s {\n\treturn %s{value: strings.Repeat(\" \", %d)}\n}\n", name, name, name, name, minLen)
	}

	fmt.Fprintf(out, "// %s is a generated YANG string length type.\n", name)
	fmt.Fprintf(out, "type %s struct {\n\tvalue string\n}\n\n", name)
	fmt.Fprintf(out, "// New%s creates a %s if the length is within bounds.\n", name, name)
	fmt.Fprintf(out, "func New%s(v string) (%s, error) {\n", name, name)
	fmt.Fprintf(out, "\tif err := cambiumValidateStringValue(v); err != nil { return %s{}, err }\n", name)
	fmt.Fprintf(out, "\tl := utf8.RuneCountInString(v)\n")
	fmt.Fprintf(out, "\tif %s {\n", check)
	fmt.Fprintf(out, "\t\treturn %s{value: v}, nil\n", name)
	fmt.Fprintf(out, "\t}\n")
	fmt.Fprintf(out, "\treturn %s{}, fmt.Errorf(\"length %%d out of bounds for %s\", l)\n", name, name)
	fmt.Fprintf(out, "}\n\n")
	fmt.Fprintf(out, "// String returns the wrapped string.\n")
	fmt.Fprintf(out, "func (l %s) String() string { return l.value }\n\n", name)
	out.WriteString(defaultExpr)
}

func (g *goEmitter) ensureEnum(name, yangName string, values []cambium.EnumValue) {
	if g.enumTypes[name] {
		return
	}
	g.enumTypes[name] = true
	view := enumView{Name: name, YangName: yangName}
	used := make(map[string]bool)
	for _, ev := range values {
		variant := safeVariantIdent(ev.Name(), used)
		view.Variants = append(view.Variants, enumVariantView{Const: name + variant, Value: ev.Value(), Name: ev.Name()})
	}
	g.typeSnippets[name] = g.renderType(tmplEnum, view)
}

func (g *goEmitter) ensureBits(name, yangName string, values []cambium.EnumValue) {
	if g.bitsTypes[name] {
		return
	}
	g.bitsTypes[name] = true
	view := bitsView{Name: name, YangName: yangName}
	for _, ev := range values {
		view.Bits = append(view.Bits, bitVariantView{Name: ev.Name(), Pos: ev.Value()})
	}
	g.typeSnippets[name] = g.renderType(tmplBits, view)
}

type identityrefMember struct {
	module    string
	name      string
	variant   string
	prefix    string
	namespace string
}

func (g *goEmitter) ensureIdentityref(name, yangName string, members []identityrefMember) {
	if g.identityrefTypes[name] {
		return
	}
	g.identityrefTypes[name] = true
	view := identityrefView{Name: name, YangName: yangName}
	for _, m := range members {
		jsonName := m.name
		if m.module != g.moduleName {
			jsonName = m.module + ":" + m.name
		}
		view.Members = append(view.Members, identityrefMemberView{
			Const:     name + m.variant,
			Name:      m.name,
			JSONName:  jsonName,
			Foreign:   m.module != g.moduleName,
			Prefix:    m.prefix,
			Namespace: m.namespace,
		})
	}
	g.helpers["xmlEscape"] = true
	g.typeSnippets[name] = g.renderType(tmplIdentityref, view)
}

func (g *goEmitter) ensureUnion(name, yangName string, members []cambium.TypeInfo, prefix, fieldIdent string) {
	if g.unionTypes[name] {
		return
	}
	g.unionTypes[name] = true
	g.helpers["xmlEscape"] = true
	g.helpers["jsonEscape"] = true

	view := unionView{Name: name, YangName: yangName}
	used := make(map[string]bool)
	for _, member := range members {
		label := unionMemberLabel(member)
		variant := safeVariantIdent(label, used)
		variantType := name + variant
		payloadType := g.unionPayloadType(name, variant, member, prefix, fieldIdent)
		view.Members = append(view.Members, unionMemberView{
			VariantType: variantType,
			Variant:     variant,
			PayloadType: payloadType,
			Wrapper:     unionMemberNeedsWrapper(member),
			Methods:     g.unionVariantMethods(name, variantType, payloadType, member),
		})
	}
	if len(view.Members) == 0 {
		view.Members = append(view.Members, unionMemberView{
			VariantType: name + "String",
			Fallback:    true,
			Methods:     g.unionVariantMethods(name, name+"String", "string", cambium.TypeInfo{}),
		})
	}
	g.typeSnippets[name] = g.renderType(tmplUnion, view)
}

func (g *goEmitter) unionPayloadType(unionName, variant string, member cambium.TypeInfo, prefix, fieldIdent string) string {
	switch r := member.Resolved().(type) {
	case cambium.ResolvedLeafRef:
		if realtype, ok := r.Realtype(); ok {
			return g.unionPayloadType(unionName, variant, *realtype, prefix, fieldIdent)
		}
		return "string"
	case cambium.ResolvedBoolean:
		return "bool"
	case cambium.ResolvedInt:
		if len(r.Range) > 0 {
			name := unionIntRangePayloadTypeName(unionName, variant)
			g.intRangeTypes[name] = intRangeInfo{kind: r.Kind, bounds: r.Range}
			return name
		}
		return goTypeForIntKind(r.Kind)
	case cambium.ResolvedDecimal64:
		g.emittedDecimal64 = true
		return "Decimal64"
	case cambium.ResolvedString:
		if len(r.Length) > 0 {
			name := unionStringLengthPayloadTypeName(unionName, variant)
			g.stringLengthTypes[name] = stringLengthInfo{bounds: r.Length}
			return name
		}
		return "string"
	case cambium.ResolvedBinary, cambium.ResolvedUnknown:
		return "string"
	case cambium.ResolvedInstanceIdentifier:
		g.emittedInstanceID = true
		g.helpers["xmlEscape"] = true
		g.helpers["jsonEscape"] = true
		return "InstanceIdentifier"
	case cambium.ResolvedEmpty:
		return "struct{}"
	case cambium.ResolvedEnumeration:
		enumName := unionName + variant + "Enum"
		g.ensureEnum(enumName, variant, r.Values())
		return enumName
	case cambium.ResolvedBits:
		bitsName := unionName + variant + "Bits"
		g.ensureBits(bitsName, variant, r.Values())
		return bitsName
	case cambium.ResolvedIdentityRef:
		members := collectIdentityrefMembers(r.Bases())
		if len(members) == 0 {
			return "string"
		}
		identName := unionName + variant + "Enum"
		g.ensureIdentityref(identName, variant, members)
		return identName
	case cambium.ResolvedUnion:
		nestedName := unionName + variant + "Union"
		g.ensureUnion(nestedName, variant, r.Members(), prefix, fieldIdent+variant)
		return nestedName
	default:
		return "string"
	}
}

func (g *goEmitter) unionVariantMethods(unionName, variantType, payloadType string, member cambium.TypeInfo) string {
	xmlExpr := ""
	xmlPrefixExpr := "return \"\", \"\", false"
	jsonExpr := ""
	stringExpr := ""
	validateExpr := "return nil"

	switch r := member.Resolved().(type) {
	case cambium.ResolvedLeafRef:
		if realtype, ok := r.Realtype(); ok {
			return g.unionVariantMethods(unionName, variantType, payloadType, *realtype)
		}
		xmlExpr = "cambiumXMLEscapeText(string(v))"
		jsonExpr = "cambiumJSONEscape(string(v))"
		stringExpr = "string(v)"
		validateExpr = "if err := cambiumValidateStringValue(string(v)); err != nil { return cambiumValidationError(path, err.Error()) }\n\treturn nil"
	case cambium.ResolvedBoolean:
		g.helpers["strconv"] = true
		xmlExpr = "strconv.FormatBool(bool(v))"
		jsonExpr = xmlExpr
		stringExpr = xmlExpr
	case cambium.ResolvedInt:
		if len(r.Range) > 0 {
			xmlExpr = fmt.Sprintf("%s(v).String()", payloadType)
			if r.Kind == cambium.IntKindI64 || r.Kind == cambium.IntKindU64 {
				jsonExpr = fmt.Sprintf("cambiumJSONEscape(%s(v).String())", payloadType)
			} else {
				jsonExpr = xmlExpr
			}
			stringExpr = xmlExpr
			validateExpr = fmt.Sprintf("if _, err := New%s(%s(v).Get()); err != nil { return cambiumValidationError(path, err.Error()) }\n\treturn nil", payloadType, payloadType)
			break
		}
		g.helpers["strconv"] = true
		if isSignedIntKind(r.Kind) {
			xmlExpr = "strconv.FormatInt(int64(v), 10)"
		} else {
			xmlExpr = "strconv.FormatUint(uint64(v), 10)"
		}
		if r.Kind == cambium.IntKindI64 || r.Kind == cambium.IntKindU64 {
			jsonExpr = fmt.Sprintf("cambiumJSONEscape(%s)", xmlExpr)
		} else {
			jsonExpr = xmlExpr
		}
		stringExpr = xmlExpr
	case cambium.ResolvedDecimal64:
		xmlExpr = "Decimal64(v).String()"
		jsonExpr = "cambiumJSONEscape(Decimal64(v).String())"
		stringExpr = xmlExpr
		fd, ranges := decimal64ValidationArgs(member)
		validateExpr = fmt.Sprintf("if err := cambiumValidateDecimal64Value(Decimal64(v), %d, %s); err != nil { return cambiumValidationError(path, err.Error()) }\n\treturn nil", fd, ranges)
	case cambium.ResolvedString:
		patterns := stringPatternLiteral(member)
		if patterns != "nil" {
			g.helpers["patternValidate"] = true
		}
		if len(r.Length) > 0 {
			xmlExpr = fmt.Sprintf("cambiumXMLEscapeText(%s(v).String())", payloadType)
			jsonExpr = fmt.Sprintf("cambiumJSONEscape(%s(v).String())", payloadType)
			stringExpr = fmt.Sprintf("%s(v).String()", payloadType)
			validateExpr = fmt.Sprintf("if _, err := New%s(%s(v).String()); err != nil { return cambiumValidationError(path, err.Error()) }\n\treturn nil", payloadType, payloadType)
			if patterns != "nil" {
				validateExpr = fmt.Sprintf("if _, err := New%s(%s(v).String()); err != nil { return cambiumValidationError(path, err.Error()) }\n\tif err := cambiumValidateStringPatterns(%s(v).String(), %s); err != nil { return cambiumValidationError(path, err.Error()) }\n\treturn nil", payloadType, payloadType, payloadType, patterns)
			}
			break
		}
		xmlExpr = "cambiumXMLEscapeText(string(v))"
		jsonExpr = "cambiumJSONEscape(string(v))"
		stringExpr = "string(v)"
		validateExpr = "if err := cambiumValidateStringValue(string(v)); err != nil { return cambiumValidationError(path, err.Error()) }\n\treturn nil"
		if patterns != "nil" {
			validateExpr = fmt.Sprintf("if err := cambiumValidateStringValue(string(v)); err != nil { return cambiumValidationError(path, err.Error()) }\n\tif err := cambiumValidateStringPatterns(string(v), %s); err != nil { return cambiumValidationError(path, err.Error()) }\n\treturn nil", patterns)
		}
	case cambium.ResolvedEnumeration:
		xmlExpr = fmt.Sprintf("cambiumXMLEscapeText(%s(v).String())", payloadType)
		jsonExpr = fmt.Sprintf("cambiumJSONEscape(%s(v).String())", payloadType)
		stringExpr = fmt.Sprintf("%s(v).String()", payloadType)
		validateExpr = fmt.Sprintf("if %s(v).AsName() == \"\" { return cambiumValidationError(path, \"invalid enum value\") }\n\treturn nil", payloadType)
	case cambium.ResolvedBits:
		xmlExpr = fmt.Sprintf("cambiumXMLEscapeText(%s(v).String())", payloadType)
		jsonExpr = fmt.Sprintf("cambiumJSONEscape(%s(v).String())", payloadType)
		stringExpr = fmt.Sprintf("%s(v).String()", payloadType)
	case cambium.ResolvedBinary:
		g.helpers["binaryParse"] = true
		xmlExpr = "cambiumXMLEscapeText(string(v))"
		jsonExpr = "cambiumJSONEscape(string(v))"
		stringExpr = "string(v)"
		validateExpr = fmt.Sprintf("if err := cambiumValidateBinaryString(string(v), %s); err != nil { return cambiumValidationError(path, err.Error()) }\n\treturn nil", binaryLengthRangeLiteral(member))
	case cambium.ResolvedIdentityRef:
		xmlExpr = fmt.Sprintf("%s(v).XMLValue()", payloadType)
		xmlPrefixExpr = fmt.Sprintf("return %s(v).XMLPrefixNS()", payloadType)
		jsonExpr = fmt.Sprintf("cambiumJSONEscape(%s(v).AsJSONName())", payloadType)
		stringExpr = fmt.Sprintf("%s(v).String()", payloadType)
		validateExpr = fmt.Sprintf("if %s(v).AsJSONName() == \"\" { return cambiumValidationError(path, \"invalid identityref value\") }\n\treturn nil", payloadType)
	case cambium.ResolvedInstanceIdentifier:
		xmlExpr = "InstanceIdentifier(v).XMLValue()"
		xmlPrefixExpr = "return InstanceIdentifier(v).XMLPrefixNS()"
		jsonExpr = "InstanceIdentifier(v).JSONValue()"
		stringExpr = "InstanceIdentifier(v).String()"
		validateExpr = "return InstanceIdentifier(v).validate(path)"
	case cambium.ResolvedUnion:
		xmlExpr = "v.Value.XMLValue()"
		xmlPrefixExpr = "return v.Value.XMLPrefixNS()"
		jsonExpr = "v.Value.JSONValue()"
		stringExpr = "v.Value.String()"
		validateExpr = "if v.Value == nil { return cambiumValidationError(path, \"invalid union value\") }\n\treturn v.Value.validate(path)"
	case cambium.ResolvedEmpty:
		xmlExpr = "\"\""
		jsonExpr = "\"[null]\""
		stringExpr = "\"\""
	default:
		xmlExpr = "cambiumXMLEscapeText(string(v))"
		jsonExpr = "cambiumJSONEscape(string(v))"
		stringExpr = "string(v)"
	}

	return fmt.Sprintf("func (%s) is%s() {}\nfunc (v %s) XMLValue() string { return %s }\nfunc (v %s) XMLPrefixNS() (string, string, bool) { %s }\nfunc (v %s) JSONValue() string { return %s }\nfunc (v %s) String() string { return %s }\nfunc (v %s) validate(path string) error { %s }\n", variantType, unionName, variantType, xmlExpr, variantType, xmlPrefixExpr, variantType, jsonExpr, variantType, stringExpr, variantType, validateExpr)
}

func unionMemberNeedsWrapper(member cambium.TypeInfo) bool {
	switch r := member.Resolved().(type) {
	case cambium.ResolvedLeafRef:
		if realtype, ok := r.Realtype(); ok {
			return unionMemberNeedsWrapper(*realtype)
		}
		return false
	case cambium.ResolvedUnion:
		return true
	default:
		return false
	}
}

func (g *goEmitter) emitCambiumStructInterface(out *strings.Builder) {
	out.WriteString(tmplCambiumStructIface)
}

func (g *goEmitter) emitStructRec(node cambium.SchemaNodeRef, structName string, out *strings.Builder) {
	if !isStructKind(node.Kind()) {
		return
	}

	var ordered []cambium.SchemaNodeRef
	switch node.Kind() {
	case cambium.SchemaNodeKindAction, cambium.SchemaNodeKindRPC:
		ordered = g.operationPayloadChildren(node)
	case cambium.SchemaNodeKindNotification:
		ordered = g.orderedChildrenList(node.DataChildren(true))
	case cambium.SchemaNodeKindList:
		ordered = orderedListChildren(node.DataChildren(true), node.ListKeys())
		ordered = append(ordered, g.operationChildren(node)...)
	default:
		ordered = g.orderedChildrenList(node.DataChildren(true))
		ordered = append(ordered, g.operationChildren(node)...)
	}
	fields := g.collectFields(structName, ordered)

	g.emitStructDefinition(structName, fields, out)
	g.emitFieldOrder(structName, fields, out)
	g.emitStructSerializers(structName, fields, node.Module().Name(), node.Namespace(), out)
	g.emitValidationMethods(structName, fields, g.validationSourceChildren(node), "", out)
	g.emitCambiumStructImpl(structName, out)

	for _, f := range fields {
		if isStructKind(f.node.Kind()) {
			g.emitStructRec(f.node, fieldConcreteType(f), out)
		}
	}
}

func (g *goEmitter) emitStructDefinition(name string, fields []fieldInfo, out *strings.Builder) {
	view := structDefView{Name: name, HasMetadata: hasMetadataTargets(fields)}
	for _, f := range fields {
		view.Fields = append(view.Fields, structFieldView{Doc: g.fieldDoc(f), Ident: f.ident, GoType: f.goType})
	}
	if view.HasMetadata {
		g.emittedMetadata = true
		g.helpers["xmlEscape"] = true
		g.helpers["jsonEscape"] = true
		g.helpers["jsonIndent"] = true
		g.needsSort = true
	}
	out.WriteString(g.renderType(tmplStructDef, view))
}

func hasMetadataTargets(fields []fieldInfo) bool {
	for _, f := range fields {
		switch f.node.Kind() {
		case cambium.SchemaNodeKindLeaf, cambium.SchemaNodeKindLeafList:
			return true
		}
	}
	return false
}

func fieldsByNode(fields []fieldInfo) map[cambium.SchemaNodeRef]fieldInfo {
	byNode := make(map[cambium.SchemaNodeRef]fieldInfo, len(fields))
	for _, f := range fields {
		byNode[f.node] = f
	}
	return byNode
}

func (g *goEmitter) fieldDoc(f fieldInfo) string {
	if desc, ok := f.node.Description(); ok && desc != "" {
		// Use first line only to keep generated lines reasonable.
		if i := strings.IndexByte(desc, '\n'); i >= 0 {
			return strings.TrimSpace(desc[:i])
		}
		return strings.TrimSpace(desc)
	}
	return fmt.Sprintf("Generated YANG %s %q", kindName(f.node.Kind()), f.wire)
}

func (g *goEmitter) emitFieldOrder(name string, fields []fieldInfo, out *strings.Builder) {
	view := fieldOrderView{Name: name}
	for _, f := range fields {
		view.Wires = append(view.Wires, f.wire)
	}
	out.WriteString(g.renderType(tmplFieldOrder, view))
}

func (g *goEmitter) emitStructSerializers(name string, fields []fieldInfo, currentModule, currentNS string, out *strings.Builder) {
	g.emitStructWriters(name, fields, currentModule, currentNS, out)

	// ToXML
	fmt.Fprintf(out, "func (n *%s) ToXML() string {\n", name)
	out.WriteString("\tvar b strings.Builder\n")
	out.WriteString("\tn.writeXML(&b, 0)\n")
	out.WriteString("\treturn b.String()\n")
	out.WriteString("}\n\n")

	// ToJSONIETF
	fmt.Fprintf(out, "func (n *%s) ToJSONIETF() string {\n", name)
	out.WriteString("\treturn n.ToJSONIETFWithDefaults(WithDefaultsExplicit)\n")
	out.WriteString("}\n\n")

	fmt.Fprintf(out, "func (n *%s) ToJSONIETFWithDefaults(mode WithDefaultsMode) string {\n", name)
	out.WriteString("\tvar b strings.Builder\n")
	out.WriteString("\tn.writeJSONWithDefaults(&b, 0, mode)\n")
	out.WriteString("\treturn b.String()\n")
	out.WriteString("}\n\n")

	g.emitStructParser(name, fields, currentModule, out)
}

func (g *goEmitter) emitStructWriters(name string, fields []fieldInfo, currentModule, currentNS string, out *strings.Builder) {
	// writeXML
	fmt.Fprintf(out, "func (n *%s) writeXML(b *strings.Builder, depth int) {\n", name)
	out.WriteString("\tindent := strings.Repeat(\" \", depth*2)\n")
	for _, f := range fields {
		g.emitFieldXML(f, currentNS, out)
	}
	out.WriteString("}\n\n")

	// writeJSON
	g.helpers["jsonIndent"] = true
	fmt.Fprintf(out, "func (n *%s) writeJSON(b *strings.Builder, depth int) {\n", name)
	out.WriteString("\tn.writeJSONWithDefaults(b, depth, WithDefaultsExplicit)\n")
	out.WriteString("}\n\n")

	fmt.Fprintf(out, "func (n *%s) writeJSONWithDefaults(b *strings.Builder, depth int, mode WithDefaultsMode) {\n", name)
	if len(fields) == 0 {
		out.WriteString("\tb.WriteString(\"{}\")\n")
	} else {
		out.WriteString("\tif !n.hasContentWithDefaults(mode) {\n")
		out.WriteString("\t\tb.WriteString(\"{}\")\n")
		out.WriteString("\t\treturn\n")
		out.WriteString("\t}\n")
		out.WriteString("\tb.WriteByte('{')\n")
		out.WriteString("\tfirst := true\n")
		byNode := fieldsByNode(fields)
		for _, f := range fields {
			g.emitFieldJSON(f, currentModule, byNode, out)
		}
		out.WriteString("\tcambiumJSONIndent(b, depth)\n")
		out.WriteString("\tb.WriteByte('}')\n")
	}
	out.WriteString("}\n\n")

	g.emitHasContent(name, fields, out)
	g.emitHasContentWithDefaults(name, fields, out)
}

func (g *goEmitter) emitHasContent(name string, fields []fieldInfo, out *strings.Builder) {
	fmt.Fprintf(out, "func (n *%s) hasContent() bool {\n", name)
	mandatory := false
	var conds []string
	for _, f := range fields {
		switch f.node.Kind() {
		case cambium.SchemaNodeKindLeaf:
			if f.optional {
				conds = append(conds, fmt.Sprintf("n.%s != nil", f.ident))
			} else {
				mandatory = true
			}
		case cambium.SchemaNodeKindLeafList:
			if strings.HasPrefix(f.goType, "UserOrderedVec[") {
				conds = append(conds, fmt.Sprintf("!n.%s.IsEmpty()", f.ident))
			} else {
				conds = append(conds, fmt.Sprintf("len(n.%s) > 0", f.ident))
			}
		case cambium.SchemaNodeKindAnyData:
			if f.optional {
				conds = append(conds, fmt.Sprintf("n.%s != nil", f.ident))
			} else {
				mandatory = true
			}
		case cambium.SchemaNodeKindContainer:
			if f.optional {
				conds = append(conds, fmt.Sprintf("n.%s != nil", f.ident))
			} else {
				conds = append(conds, fmt.Sprintf("n.%s.hasContent()", f.ident))
			}
		case cambium.SchemaNodeKindList:
			if strings.HasPrefix(f.goType, "UserOrderedVec[") {
				conds = append(conds, fmt.Sprintf("!n.%s.IsEmpty()", f.ident))
			} else {
				conds = append(conds, fmt.Sprintf("len(n.%s) > 0", f.ident))
			}
		case cambium.SchemaNodeKindAction, cambium.SchemaNodeKindNotification:
			conds = append(conds, fmt.Sprintf("n.%s != nil", f.ident))
		}
	}
	if mandatory {
		out.WriteString("\treturn true\n")
	} else if len(conds) == 0 {
		out.WriteString("\treturn false\n")
	} else {
		fmt.Fprintf(out, "\treturn %s\n", strings.Join(conds, " || "))
	}
	out.WriteString("}\n\n")
}

func (g *goEmitter) emitHasContentWithDefaults(name string, fields []fieldInfo, out *strings.Builder) {
	fmt.Fprintf(out, "func (n *%s) hasContentWithDefaults(mode WithDefaultsMode) bool {\n", name)
	out.WriteString("\tif mode == WithDefaultsTrim {\n")
	g.emitTrimHasContentChecks(fields, out)
	out.WriteString("\t\treturn false\n")
	out.WriteString("\t}\n")
	out.WriteString("\tif n.hasContent() { return true }\n")
	var conds []string
	seenConds := make(map[string]bool)
	addCond := func(cond string) {
		if seenConds[cond] {
			return
		}
		seenConds[cond] = true
		conds = append(conds, cond)
	}
	byNode := fieldsByNode(fields)
	for _, f := range fields {
		switch f.node.Kind() {
		case cambium.SchemaNodeKindLeaf:
			if _, ok := f.node.DefaultValue(); ok {
				cond := "mode == WithDefaultsAll || mode == WithDefaultsAllTagged"
				if guard := g.choiceDefaultEmissionGuard("n", f, byNode); guard != "" {
					cond = "(" + cond + ") && (" + guard + ")"
				}
				addCond(cond)
			}
		case cambium.SchemaNodeKindLeafList:
			if len(f.node.DefaultValues()) > 0 {
				cond := "mode == WithDefaultsAll || mode == WithDefaultsAllTagged"
				if guard := g.choiceDefaultEmissionGuard("n", f, byNode); guard != "" {
					cond = "(" + cond + ") && (" + guard + ")"
				}
				addCond(cond)
			}
		case cambium.SchemaNodeKindContainer:
			if f.optional {
				addCond(fmt.Sprintf("n.%s != nil && n.%s.hasContentWithDefaults(mode)", f.ident, f.ident))
			} else {
				cond := fmt.Sprintf("n.%s.hasContentWithDefaults(mode)", f.ident)
				if guard := g.choiceDefaultEmissionGuard("n", f, byNode); guard != "" {
					cond += " && (" + guard + ")"
				}
				addCond(cond)
			}
		case cambium.SchemaNodeKindAction, cambium.SchemaNodeKindNotification:
			addCond(fmt.Sprintf("n.%s != nil && n.%s.hasContentWithDefaults(mode)", f.ident, f.ident))
		}
	}
	if len(conds) == 0 {
		out.WriteString("\treturn false\n")
	} else {
		fmt.Fprintf(out, "\treturn %s\n", strings.Join(conds, " || "))
	}
	out.WriteString("}\n\n")
}

func (g *goEmitter) emitTrimHasContentChecks(fields []fieldInfo, out *strings.Builder) {
	out.WriteString("\t\ttrimHasContent := false\n")
	for _, f := range fields {
		switch f.node.Kind() {
		case cambium.SchemaNodeKindLeaf:
			if defaultValue, ok := f.node.DefaultEntry(); ok {
				if f.optional {
					valueRef := "(*n." + f.ident + ")"
					if f.isUnion {
						valueRef = "n." + f.ident
					}
					fmt.Fprintf(out, "\t\tif n.%s != nil && %s != %s { return true }\n", f.ident, g.jsonLiteralExpr(valueRef, f), g.defaultJSONLiteralExpr(f, defaultValue))
				} else {
					fmt.Fprintf(out, "\t\tif %s != %s { return true }\n", g.jsonLiteralExpr("n."+f.ident, f), g.defaultJSONLiteralExpr(f, defaultValue))
				}
			} else if f.optional {
				fmt.Fprintf(out, "\t\tif n.%s != nil { return true }\n", f.ident)
			} else {
				out.WriteString("\t\ttrimHasContent = true\n")
			}
		case cambium.SchemaNodeKindLeafList:
			defaults := f.node.DefaultEntries()
			if len(defaults) > 0 {
				defaultVar := g.emitLeafListDefaultCheck("n", f, defaults, out, "\t\t")
				if strings.HasPrefix(f.goType, "UserOrderedVec[") {
					fmt.Fprintf(out, "\t\tif n.%s.Len() > 0 && !%s { return true }\n", f.ident, defaultVar)
				} else {
					fmt.Fprintf(out, "\t\tif len(n.%s) > 0 && !%s { return true }\n", f.ident, defaultVar)
				}
			} else if strings.HasPrefix(f.goType, "UserOrderedVec[") {
				fmt.Fprintf(out, "\t\tif !n.%s.IsEmpty() { return true }\n", f.ident)
			} else {
				fmt.Fprintf(out, "\t\tif len(n.%s) > 0 { return true }\n", f.ident)
			}
		case cambium.SchemaNodeKindAnyData:
			if f.optional {
				fmt.Fprintf(out, "\t\tif n.%s != nil { return true }\n", f.ident)
			} else {
				out.WriteString("\t\ttrimHasContent = true\n")
			}
		case cambium.SchemaNodeKindContainer:
			if f.optional {
				fmt.Fprintf(out, "\t\tif n.%s != nil { return true }\n", f.ident)
			} else {
				fmt.Fprintf(out, "\t\tif n.%s.hasContentWithDefaults(mode) { return true }\n", f.ident)
			}
		case cambium.SchemaNodeKindList:
			if strings.HasPrefix(f.goType, "UserOrderedVec[") {
				fmt.Fprintf(out, "\t\tif !n.%s.IsEmpty() { return true }\n", f.ident)
			} else {
				fmt.Fprintf(out, "\t\tif len(n.%s) > 0 { return true }\n", f.ident)
			}
		case cambium.SchemaNodeKindAction, cambium.SchemaNodeKindNotification:
			fmt.Fprintf(out, "\t\tif n.%s != nil { return true }\n", f.ident)
		}
	}
	out.WriteString("\t\tif trimHasContent { return true }\n")
}

func (g *goEmitter) emitLeafListDefaultCheck(owner string, f fieldInfo, defaults []cambium.DefaultValue, out *strings.Builder, indent string) string {
	defaults = g.orderedDefaultValues(defaults, f)
	defaultVar := "isDefault" + f.ident
	fmt.Fprintf(out, "%s%s := false\n", indent, defaultVar)
	if strings.HasPrefix(f.goType, "UserOrderedVec[") {
		fmt.Fprintf(out, "%sif %s.%s.Len() == %d {\n", indent, owner, f.ident, len(defaults))
		fmt.Fprintf(out, "%s\t%s = true\n", indent, defaultVar)
		for i, defaultValue := range defaults {
			valueVar := fmt.Sprintf("default%sItem%d", f.ident, i)
			okVar := fmt.Sprintf("default%sOK%d", f.ident, i)
			fmt.Fprintf(out, "%s\t%s, %s := %s.%s.Get(%d)\n", indent, valueVar, okVar, owner, f.ident, i)
			fmt.Fprintf(out, "%s\tif !%s || %s != %s { %s = false }\n", indent, okVar, g.jsonLiteralExpr(valueVar, f), g.defaultJSONLiteralExpr(f, defaultValue), defaultVar)
		}
		fmt.Fprintf(out, "%s}\n", indent)
		return defaultVar
	}

	fmt.Fprintf(out, "%sif len(%s.%s) == %d {\n", indent, owner, f.ident, len(defaults))
	itemsExpr := fieldItemsExpr(owner, f.ident, f)
	if g.shouldSortCollection(f) {
		g.needsSort = true
		itemsExpr = "defaultOrdered" + f.ident
		fmt.Fprintf(out, "%s\t%s := append([]%s(nil), %s.%s...)\n", indent, itemsExpr, fieldConcreteType(f), owner, f.ident)
		g.emitSortSlice(itemsExpr, f, out, indent+"\t")
	}
	fmt.Fprintf(out, "%s\t%s = true\n", indent, defaultVar)
	for i, defaultValue := range defaults {
		valueRef := fmt.Sprintf("%s[%d]", itemsExpr, i)
		fmt.Fprintf(out, "%s\tif %s != %s { %s = false }\n", indent, g.jsonLiteralExpr(valueRef, f), g.defaultJSONLiteralExpr(f, defaultValue), defaultVar)
	}
	fmt.Fprintf(out, "%s}\n", indent)
	return defaultVar
}

func (g *goEmitter) emitCambiumStructImpl(name string, out *strings.Builder) {
	// In Go, methods implement interfaces implicitly; no explicit impl needed.
	// Keep a compile-time assertion so moving a method is a build break.
	fmt.Fprintf(out, "var _ CambiumStruct = (*%s)(nil)\n\n", name)
}

func (g *goEmitter) recordEmitError(err error) {
	if g.emitErr == nil {
		g.emitErr = err
	}
}

func findFieldForNode(fields []fieldInfo, node cambium.SchemaNodeRef) (fieldInfo, bool) {
	for _, field := range fields {
		if field.node == node {
			return field, true
		}
	}
	return fieldInfo{}, false
}

func (g *goEmitter) emitRootStruct(fields []fieldInfo, out *strings.Builder) {
	name := g.modulePascal

	g.emitStructDefinition(name, fields, out)
	g.emitFieldOrder(name, fields, out)

	// Root XML serializer.
	fmt.Fprintf(out, "func (m *%s) ToXML() string {\n", name)
	out.WriteString("\tvar b strings.Builder\n")
	for _, f := range fields {
		g.emitTopLevelXML(f, out)
	}
	out.WriteString("\treturn b.String()\n")
	out.WriteString("}\n\n")

	// Root JSON serializer.
	g.helpers["jsonIndent"] = true
	fmt.Fprintf(out, "func (m *%s) ToJSONIETF() string {\n", name)
	out.WriteString("\treturn m.ToJSONIETFWithDefaults(WithDefaultsExplicit)\n")
	out.WriteString("}\n\n")

	fmt.Fprintf(out, "func (m *%s) ToJSONIETFWithDefaults(mode WithDefaultsMode) string {\n", name)
	out.WriteString("\tvar b strings.Builder\n")
	out.WriteString("\tw := &b\n")
	if len(fields) == 0 {
		out.WriteString("\tw.WriteString(\"{}\\n\")\n")
		out.WriteString("\treturn b.String()\n")
		out.WriteString("}\n\n")
		g.emitRootParser(name, fields, out)
		g.emitValidationMethods(name, fields, g.documentValidationSourceChildren(), "/"+g.moduleName, out)
		g.emitCambiumStructImpl(name, out)
		fmt.Fprintf(out, "// %sModuleNS is the XML namespace of module %q.\n", name, g.moduleName)
		fmt.Fprintf(out, "const %sModuleNS = %q\n\n", name, g.ns)
		fmt.Fprintf(out, "// %sModuleName is the YANG module name.\n", name)
		fmt.Fprintf(out, "const %sModuleName = %q\n\n", name, g.moduleName)
		return
	}
	out.WriteString("\tw.WriteByte('{')\n")
	out.WriteString("\tfirst := true\n")
	byNode := fieldsByNode(fields)
	for _, f := range fields {
		g.emitTopLevelJSON(f, byNode, out)
	}
	out.WriteString("\tcambiumJSONIndent(w, 0)\n")
	out.WriteString("\tw.WriteByte('}')\n")
	out.WriteString("\tw.WriteByte('\\n')\n")
	out.WriteString("\treturn b.String()\n")
	out.WriteString("}\n\n")

	g.emitRootParser(name, fields, out)
	g.emitValidationMethods(name, fields, g.documentValidationSourceChildren(), "/"+g.moduleName, out)
	g.emitCambiumStructImpl(name, out)

	// Module constants.
	fmt.Fprintf(out, "// %sModuleNS is the XML namespace of module %q.\n", name, g.moduleName)
	fmt.Fprintf(out, "const %sModuleNS = %q\n\n", name, g.ns)
	fmt.Fprintf(out, "// %sModuleName is the YANG module name.\n", name)
	fmt.Fprintf(out, "const %sModuleName = %q\n\n", name, g.moduleName)
}

func (g *goEmitter) emitOperationDocuments(out *strings.Builder) {
	for rpc := range g.module.RPCs().Iter() {
		input := g.operationInputSource(rpc)
		output := g.operationOutputSource(rpc)
		switch {
		case input.Kind() != cambium.SchemaNodeKindUnknown:
			g.emitOperationDocument(rpc, input, "RPC", "/"+rpc.Module().Name()+"/"+rpc.Name(), out)
			if output.Kind() != cambium.SchemaNodeKindUnknown {
				g.emitOperationDocument(rpc, output, "RPCOutput", "/"+rpc.Module().Name()+"/"+rpc.Name()+"/output", out)
			}
		case output.Kind() != cambium.SchemaNodeKindUnknown:
			g.emitOperationDocument(rpc, output, "RPC", "/"+rpc.Module().Name()+"/"+rpc.Name(), out)
		default:
			g.emitOperationDocument(rpc, rpc, "RPC", "/"+rpc.Module().Name()+"/"+rpc.Name(), out)
		}
	}
	for notif := range g.module.Notifications().Iter() {
		g.emitOperationDocument(notif, notif, "Notification", "/"+notif.Module().Name()+"/"+notif.Name(), out)
	}
}

func (g *goEmitter) emitOperationDocument(op, source cambium.SchemaNodeRef, suffix, validationPath string, out *strings.Builder) {
	structName := g.modulePascal + toPascalCase(op.Name()) + suffix
	fields := g.collectFields(structName, g.operationSourcePayloadChildren(op, source))

	g.emitStructDefinition(structName, fields, out)
	g.emitFieldOrder(structName, fields, out)
	g.emitStructWriters(structName, fields, op.Module().Name(), op.Namespace(), out)
	g.emitStructParser(structName, fields, op.Module().Name(), out)
	g.emitOperationRootSerializers(structName, op, out)
	g.emitOperationRootParser(structName, op, out)
	g.emitValidationMethods(structName, fields, g.operationSourceValidationChildren(source), validationPath, out)
	g.emitCambiumStructImpl(structName, out)

	for _, f := range fields {
		if isStructKind(f.node.Kind()) {
			g.emitStructRec(f.node, fieldConcreteType(f), out)
		}
	}
}

func (g *goEmitter) operationSourcePayloadChildren(op, source cambium.SchemaNodeRef) []cambium.SchemaNodeRef {
	if source.Kind() != cambium.SchemaNodeKindUnknown && source != op {
		return g.orderedChildrenList(source.DataChildren(true))
	}
	return g.orderedChildrenList(op.DataChildren(true))
}

func (g *goEmitter) operationPayloadChildren(op cambium.SchemaNodeRef) []cambium.SchemaNodeRef {
	source := g.operationPayloadSource(op)
	if source.Name() != "" {
		return g.orderedChildrenList(source.DataChildren(true))
	}
	return g.orderedChildrenList(op.DataChildren(true))
}

func (g *goEmitter) operationPayloadSource(op cambium.SchemaNodeRef) cambium.SchemaNodeRef {
	if op.Kind() == cambium.SchemaNodeKindRPC || op.Kind() == cambium.SchemaNodeKindAction {
		var output cambium.SchemaNodeRef
		for child := range op.Children().Iter() {
			switch child.Kind() {
			case cambium.SchemaNodeKindInput:
				if child.DataChildren(true).Len() > 0 {
					return child
				}
			case cambium.SchemaNodeKindOutput:
				output = child
			}
		}
		if output.Name() != "" {
			return output
		}
	}
	return op
}

func (g *goEmitter) operationInputSource(op cambium.SchemaNodeRef) cambium.SchemaNodeRef {
	if op.Kind() != cambium.SchemaNodeKindRPC && op.Kind() != cambium.SchemaNodeKindAction {
		return cambium.SchemaNodeRef{}
	}
	for child := range op.Children().Iter() {
		if child.Kind() == cambium.SchemaNodeKindInput && child.DataChildren(true).Len() > 0 {
			return child
		}
	}
	return cambium.SchemaNodeRef{}
}

func (g *goEmitter) operationOutputSource(op cambium.SchemaNodeRef) cambium.SchemaNodeRef {
	if op.Kind() != cambium.SchemaNodeKindRPC && op.Kind() != cambium.SchemaNodeKindAction {
		return cambium.SchemaNodeRef{}
	}
	for child := range op.Children().Iter() {
		if child.Kind() == cambium.SchemaNodeKindOutput && child.DataChildren(true).Len() > 0 {
			return child
		}
	}
	return cambium.SchemaNodeRef{}
}

func (g *goEmitter) emitOperationRootSerializers(name string, op cambium.SchemaNodeRef, out *strings.Builder) {
	wire := op.Name()
	moduleName := op.Module().Name()
	ns := op.Namespace()
	nsAttr := staticXMLNSAttr(ns)

	fmt.Fprintf(out, "func (n *%s) ToXML() string {\n", name)
	out.WriteString("\tvar b strings.Builder\n")
	out.WriteString("\tif n.hasContent() {\n")
	fmt.Fprintf(out, "\t\tb.WriteString(\"<%s%s>\\n\")\n", wire, nsAttr)
	out.WriteString("\t\tn.writeXML(&b, 1)\n")
	fmt.Fprintf(out, "\t\tb.WriteString(\"</%s>\\n\")\n", wire)
	out.WriteString("\t} else {\n")
	fmt.Fprintf(out, "\t\tb.WriteString(\"<%s%s/>\\n\")\n", wire, nsAttr)
	out.WriteString("\t}\n")
	out.WriteString("\treturn b.String()\n")
	out.WriteString("}\n\n")

	g.helpers["jsonIndent"] = true
	fmt.Fprintf(out, "func (n *%s) ToJSONIETF() string {\n", name)
	out.WriteString("\treturn n.ToJSONIETFWithDefaults(WithDefaultsExplicit)\n")
	out.WriteString("}\n\n")

	fmt.Fprintf(out, "func (n *%s) ToJSONIETFWithDefaults(mode WithDefaultsMode) string {\n", name)
	out.WriteString("\tvar b strings.Builder\n")
	out.WriteString("\tw := &b\n")
	out.WriteString("\tw.WriteByte('{')\n")
	out.WriteString("\tcambiumJSONIndent(w, 1)\n")
	fmt.Fprintf(out, "\tw.WriteString(\"\\\"%s:%s\\\": \")\n", moduleName, wire)
	out.WriteString("\tn.writeJSONWithDefaults(w, 1, mode)\n")
	out.WriteString("\tcambiumJSONIndent(w, 0)\n")
	out.WriteString("\tw.WriteByte('}')\n")
	out.WriteString("\tw.WriteByte('\\n')\n")
	out.WriteString("\treturn b.String()\n")
	out.WriteString("}\n\n")
}

func intBitSizeForGoType(goType string) int {
	switch goType {
	case "int8", "uint8":
		return 8
	case "int16", "uint16":
		return 16
	case "int32", "uint32":
		return 32
	default:
		return 64
	}
}

func intKindBitSize(kind cambium.IntKind) int {
	switch kind {
	case cambium.IntKindI8, cambium.IntKindU8:
		return 8
	case cambium.IntKindI16, cambium.IntKindU16:
		return 16
	case cambium.IntKindI32, cambium.IntKindU32:
		return 32
	default:
		return 64
	}
}

func decimal64TypeInfo(node cambium.SchemaNodeRef) (cambium.TypeInfo, bool) {
	info, ok := node.LeafType()
	if !ok {
		return cambium.TypeInfo{}, false
	}
	return decimal64TypeInfoForType(info)
}

func decimal64TypeInfoForType(info cambium.TypeInfo) (cambium.TypeInfo, bool) {
	switch r := info.Resolved().(type) {
	case cambium.ResolvedDecimal64:
		return info, true
	case cambium.ResolvedLeafRef:
		if realtype, ok := r.Realtype(); ok {
			return decimal64TypeInfoForType(*realtype)
		}
	}
	return cambium.TypeInfo{}, false
}

func parseDecimal64BoundRaw(bound string, fractionDigits uint8) int64 {
	switch bound {
	case "min":
		return -1 << 63
	case "max":
		return 1<<63 - 1
	}
	neg := strings.HasPrefix(bound, "-")
	text := strings.TrimPrefix(bound, "-")
	wholeText, fracText, ok := strings.Cut(text, ".")
	if !ok {
		fracText = ""
	}
	for len(fracText) < int(fractionDigits) {
		fracText += "0"
	}
	if len(fracText) > int(fractionDigits) {
		fracText = fracText[:fractionDigits]
	}
	if wholeText == "" {
		wholeText = "0"
	}
	whole := new(big.Int)
	whole.SetString(wholeText, 10)
	scale := new(big.Int).Exp(big.NewInt(10), big.NewInt(int64(fractionDigits)), nil)
	raw := new(big.Int).Mul(whole, scale)
	if fracText != "" {
		frac := new(big.Int)
		frac.SetString(fracText, 10)
		raw.Add(raw, frac)
	}
	if neg {
		raw.Neg(raw)
	}
	if raw.IsInt64() {
		return raw.Int64()
	}
	if neg {
		return -1 << 63
	}
	return 1<<63 - 1
}

func binaryTypeInfo(node cambium.SchemaNodeRef) (cambium.TypeInfo, bool) {
	info, ok := node.LeafType()
	if !ok {
		return cambium.TypeInfo{}, false
	}
	return binaryTypeInfoForType(info)
}

func binaryTypeInfoForType(info cambium.TypeInfo) (cambium.TypeInfo, bool) {
	switch r := info.Resolved().(type) {
	case cambium.ResolvedBinary:
		return info, true
	case cambium.ResolvedLeafRef:
		if realtype, ok := r.Realtype(); ok {
			return binaryTypeInfoForType(*realtype)
		}
	}
	return cambium.TypeInfo{}, false
}

func binaryLengthRangeLiteral(info cambium.TypeInfo) string {
	r, ok := info.Resolved().(cambium.ResolvedBinary)
	if !ok || len(r.Length) == 0 {
		return "nil"
	}
	parts := make([]string, 0, len(r.Length))
	for _, bound := range r.Length {
		parts = append(parts, fmt.Sprintf("{min: %d, max: %d}", parseLengthBound(bound.Min()), parseLengthBound(bound.Max())))
	}
	return "[]cambiumBinaryLengthRange{" + strings.Join(parts, ", ") + "}"
}

func stringValueType(node cambium.SchemaNodeRef) bool {
	info, ok := node.LeafType()
	if !ok {
		return false
	}
	return stringValueTypeInfo(info)
}

func stringValueTypeInfo(info cambium.TypeInfo) bool {
	switch r := info.Resolved().(type) {
	case cambium.ResolvedString:
		return true
	case cambium.ResolvedLeafRef:
		if realtype, ok := r.Realtype(); ok {
			return stringValueTypeInfo(*realtype)
		}
	}
	return false
}

func stringPatternInfo(node cambium.SchemaNodeRef) (cambium.TypeInfo, bool) {
	info, ok := node.LeafType()
	if !ok {
		return cambium.TypeInfo{}, false
	}
	return stringPatternInfoForType(info)
}

func stringPatternInfoForType(info cambium.TypeInfo) (cambium.TypeInfo, bool) {
	switch r := info.Resolved().(type) {
	case cambium.ResolvedString:
		return info, len(r.Patterns) > 0
	case cambium.ResolvedLeafRef:
		if realtype, ok := r.Realtype(); ok {
			return stringPatternInfoForType(*realtype)
		}
	}
	return cambium.TypeInfo{}, false
}

func stringPatternLiteral(info cambium.TypeInfo) string {
	r, ok := info.Resolved().(cambium.ResolvedString)
	if !ok || len(r.Patterns) == 0 {
		return "nil"
	}
	parts := make([]string, 0, len(r.Patterns))
	for _, p := range r.Patterns {
		parts = append(parts, fmt.Sprintf("{expr: %s, nativeExpr: %s, inverted: %t}", strconv.Quote(p.Regex()), strconv.Quote(xsdregex.NativePattern(p.Regex())), p.IsInverted()))
	}
	return "[]cambiumStringPattern{" + strings.Join(parts, ", ") + "}"
}

func (g *goEmitter) collectFields(prefix string, children []cambium.SchemaNodeRef) []fieldInfo {
	fields := make([]fieldInfo, 0, len(children))
	used := make(map[string]bool)
	usedTypeComponents := make(map[string]bool)
	for _, child := range children {
		mod := child.Module()
		ident := safeFieldIdent(child.Name(), used)
		typeIdent := safeTypeIdent(child.Name(), usedTypeComponents)
		goType, optional, jsonKind, isNewtype, intSigned, isEnum, isBits, isIdentityref, isUnion := g.fieldType(prefix, child, ident, typeIdent)
		fields = append(fields, fieldInfo{
			node:          child,
			ident:         ident,
			wire:          child.Name(),
			moduleName:    mod.Name(),
			namespace:     mod.Namespace(),
			goType:        goType,
			optional:      optional,
			jsonKind:      jsonKind,
			isNewtype:     isNewtype,
			intSigned:     intSigned,
			isEnum:        isEnum,
			isBits:        isBits,
			isIdentityref: isIdentityref,
			isUnion:       isUnion,
		})
	}
	return fields
}

func (g *goEmitter) fieldType(prefix string, node cambium.SchemaNodeRef, fieldIdent, typeIdent string) (goType string, optional bool, jsonKind string, isNewtype bool, intSigned bool, isEnum bool, isBits bool, isIdentityref bool, isUnion bool) {
	switch node.Kind() {
	case cambium.SchemaNodeKindLeaf, cambium.SchemaNodeKindLeafList:
		base, jsonKind, isNewtype, intSigned, isEnum, isBits, isIdentityref, isUnion := g.scalarType(prefix, node, fieldIdent)
		if node.Kind() == cambium.SchemaNodeKindLeafList {
			if node.OrderedBy() == cambium.OrderedByUser {
				g.emittedUserOrdered = true
				return "UserOrderedVec[" + base + "]", false, jsonKind, false, intSigned, isEnum, isBits, isIdentityref, isUnion
			}
			return "[]" + base, false, jsonKind, false, intSigned, isEnum, isBits, isIdentityref, isUnion
		}
		optional = (!node.IsMandatory() || node.IsChoiceDescendant() || len(node.Whens()) > 0) && !node.IsListKey()
		if optional && !isUnion {
			base = "*" + base
		}
		return base, optional, jsonKind, isNewtype, intSigned, isEnum, isBits, isIdentityref, isUnion
	case cambium.SchemaNodeKindAnyData:
		g.emittedAnyData = true
		optional = !node.IsMandatory() || node.IsChoiceDescendant() || len(node.Whens()) > 0
		if optional {
			return "*AnyData", optional, "AnyData", false, false, false, false, false, false
		}
		return "AnyData", optional, "AnyData", false, false, false, false, false, false
	case cambium.SchemaNodeKindContainer:
		structName := prefix + typeIdent
		optional = node.IsPresenceContainer()
		if optional {
			structName = "*" + structName
		}
		return structName, optional, "String", false, false, false, false, false, false
	case cambium.SchemaNodeKindAction, cambium.SchemaNodeKindNotification:
		structName := prefix + typeIdent
		return "*" + structName, true, "String", false, false, false, false, false, false
	case cambium.SchemaNodeKindList:
		entryName := prefix + typeIdent + "Entry"
		if node.OrderedBy() == cambium.OrderedByUser {
			g.emittedUserOrdered = true
			return "UserOrderedVec[" + entryName + "]", false, "String", false, false, false, false, false, false
		}
		return "[]" + entryName, false, "String", false, false, false, false, false, false
	default:
		return "string", false, "String", false, false, false, false, false, false
	}
}

func (g *goEmitter) scalarType(prefix string, node cambium.SchemaNodeRef, fieldIdent string) (goType string, jsonKind string, isNewtype bool, intSigned bool, isEnum bool, isBits bool, isIdentityref bool, isUnion bool) {
	info, ok := node.LeafType()
	if !ok {
		return "string", "String", false, false, false, false, false, false
	}
	return g.scalarTypeForInfo(prefix, node.Name(), info, fieldIdent)
}

func (g *goEmitter) scalarTypeForInfo(prefix, yangName string, info cambium.TypeInfo, fieldIdent string) (goType string, jsonKind string, isNewtype bool, intSigned bool, isEnum bool, isBits bool, isIdentityref bool, isUnion bool) {
	switch r := info.Resolved().(type) {
	case cambium.ResolvedLeafRef:
		if realtype, ok := r.Realtype(); ok {
			return g.scalarTypeForInfo(prefix, yangName, *realtype, fieldIdent)
		}
		return "string", "String", false, false, false, false, false, false
	case cambium.ResolvedBoolean:
		return "bool", "Bool", false, false, false, false, false, false
	case cambium.ResolvedInt:
		jsonKind = "BareNumber"
		if jsonIntegerKindQuoted(r.Kind) {
			jsonKind = "QuotedNumber"
		}
		intSigned = isSignedIntKind(r.Kind)
		if len(r.Range) > 0 {
			name := prefix + toPascalCase(fieldIdent) + "Range"
			g.intRangeTypes[name] = intRangeInfo{kind: r.Kind, bounds: r.Range}
			return name, jsonKind, true, intSigned, false, false, false, false
		}
		return goTypeForIntKind(r.Kind), jsonKind, false, intSigned, false, false, false, false
	case cambium.ResolvedDecimal64:
		g.emittedDecimal64 = true
		return "Decimal64", "QuotedNumber", true, false, false, false, false, false
	case cambium.ResolvedString:
		if len(r.Length) > 0 {
			name := prefix + toPascalCase(fieldIdent) + "Length"
			g.stringLengthTypes[name] = stringLengthInfo{bounds: r.Length}
			return name, "String", true, false, false, false, false, false
		}
		return "string", "String", false, false, false, false, false, false
	case cambium.ResolvedEmpty:
		return "struct{}", "Empty", false, false, false, false, false, false
	case cambium.ResolvedEnumeration:
		name := prefix + toPascalCase(fieldIdent) + "Enum"
		g.ensureEnum(name, yangName, r.Values())
		return name, "String", false, false, true, false, false, false
	case cambium.ResolvedBits:
		name := prefix + toPascalCase(fieldIdent) + "Bits"
		g.ensureBits(name, yangName, r.Values())
		return name, "String", false, false, false, true, false, false
	case cambium.ResolvedIdentityRef:
		members := collectIdentityrefMembers(r.Bases())
		if len(members) == 0 {
			return "string", "String", false, false, false, false, false, false
		}
		name := prefix + toPascalCase(fieldIdent) + "Enum"
		g.ensureIdentityref(name, yangName, members)
		return name, "String", false, false, false, false, true, false
	case cambium.ResolvedUnion:
		name := prefix + toPascalCase(fieldIdent) + "Union"
		g.ensureUnion(name, yangName, r.Members(), prefix, fieldIdent)
		return name, "String", false, false, false, false, false, true
	case cambium.ResolvedBinary:
		return "string", "String", false, false, false, false, false, false
	case cambium.ResolvedInstanceIdentifier:
		g.emittedInstanceID = true
		g.helpers["xmlEscape"] = true
		g.helpers["jsonEscape"] = true
		return "InstanceIdentifier", "InstanceIdentifier", false, false, false, false, false, false
	default:
		return "string", "String", false, false, false, false, false, false
	}
}

func (g *goEmitter) orderedChildrenList(children cambium.SchemaChildren) []cambium.SchemaNodeRef {
	var all []cambium.SchemaNodeRef
	for child := range children.Iter() {
		switch {
		case isEmittedKind(child.Kind()):
			all = append(all, child)
		case child.Kind() == cambium.SchemaNodeKindChoice || child.Kind() == cambium.SchemaNodeKindCase:
			all = append(all, g.orderedChildrenList(child.DataChildren(true))...)
		}
	}
	return all
}

func schemaChildrenList(children cambium.SchemaChildren) []cambium.SchemaNodeRef {
	var out []cambium.SchemaNodeRef
	for child := range children.Iter() {
		out = append(out, child)
	}
	return out
}

func (g *goEmitter) operationChildren(node cambium.SchemaNodeRef) []cambium.SchemaNodeRef {
	var ops []cambium.SchemaNodeRef
	for child := range node.Children().Iter() {
		switch child.Kind() {
		case cambium.SchemaNodeKindAction, cambium.SchemaNodeKindNotification:
			ops = append(ops, child)
		}
	}
	return ops
}

func orderedListChildren(allChildren, keys cambium.SchemaChildren) []cambium.SchemaNodeRef {
	keySet := make(map[string]struct{})
	for key := range keys.Iter() {
		keySet[key.Name()] = struct{}{}
	}

	var keysOrdered, others []cambium.SchemaNodeRef
	for child := range allChildren.Iter() {
		if !isEmittedKind(child.Kind()) {
			continue
		}
		if _, ok := keySet[child.Name()]; ok {
			keysOrdered = append(keysOrdered, child)
		} else {
			others = append(others, child)
		}
	}

	// Reorder keys to match key-statement order.
	ordered := make([]cambium.SchemaNodeRef, 0, len(keysOrdered)+len(others))
	for key := range keys.Iter() {
		for _, k := range keysOrdered {
			if k.Name() == key.Name() {
				ordered = append(ordered, k)
				break
			}
		}
	}
	// Append any keys not in key-statement order (defensive).
	for _, k := range keysOrdered {
		found := false
		for _, o := range ordered {
			if o.Name() == k.Name() {
				found = true
				break
			}
		}
		if !found {
			ordered = append(ordered, k)
		}
	}
	ordered = append(ordered, others...)
	return ordered
}

func isStructKind(k cambium.SchemaNodeKind) bool {
	return k == cambium.SchemaNodeKindContainer ||
		k == cambium.SchemaNodeKindList ||
		k == cambium.SchemaNodeKindRPC ||
		k == cambium.SchemaNodeKindAction ||
		k == cambium.SchemaNodeKindNotification
}

func isEmittedKind(k cambium.SchemaNodeKind) bool {
	switch k {
	case cambium.SchemaNodeKindLeaf, cambium.SchemaNodeKindLeafList,
		cambium.SchemaNodeKindContainer, cambium.SchemaNodeKindList,
		cambium.SchemaNodeKindAnyData:
		return true
	}
	return false
}

func kindName(k cambium.SchemaNodeKind) string {
	switch k {
	case cambium.SchemaNodeKindContainer:
		return "container"
	case cambium.SchemaNodeKindLeaf:
		return "leaf"
	case cambium.SchemaNodeKindLeafList:
		return "leaf-list"
	case cambium.SchemaNodeKindList:
		return "list"
	case cambium.SchemaNodeKindAnyData:
		return "anydata"
	default:
		return "node"
	}
}

func collectIdentityrefMembers(bases []cambium.Identity) []identityrefMember {
	seen := make(map[string]bool)
	var out []identityrefMember
	add := func(id cambium.Identity) {
		mod := id.Module()
		key := mod.Name() + ":" + id.Name()
		if seen[key] {
			return
		}
		seen[key] = true
		out = append(out, identityrefMember{
			module:    mod.Name(),
			name:      id.Name(),
			prefix:    mod.Prefix(),
			namespace: mod.Namespace(),
		})
	}
	for _, base := range bases {
		add(base)
		for _, derived := range base.Derived() {
			add(derived)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].module+":"+out[i].name < out[j].module+":"+out[j].name
	})
	usedVariants := make(map[string]bool, len(out))
	for i := range out {
		out[i].variant = safeVariantIdent(out[i].name, usedVariants)
	}
	return out
}

func unionMemberLabel(info cambium.TypeInfo) string {
	if name, ok := info.TypedefName(); ok {
		return toPascalCase(name)
	}
	switch r := info.Resolved().(type) {
	case cambium.ResolvedBoolean:
		return "Boolean"
	case cambium.ResolvedInt:
		return intKindLabel(r.Kind)
	case cambium.ResolvedDecimal64:
		return "Decimal64"
	case cambium.ResolvedEnumeration:
		return "Enumeration"
	case cambium.ResolvedBits:
		return "Bits"
	case cambium.ResolvedIdentityRef:
		return "Identityref"
	case cambium.ResolvedString:
		return "String"
	case cambium.ResolvedBinary:
		return "Binary"
	case cambium.ResolvedInstanceIdentifier:
		return "InstanceIdentifier"
	case cambium.ResolvedEmpty:
		return "Empty"
	case cambium.ResolvedLeafRef:
		return "Leafref"
	case cambium.ResolvedUnion:
		return "Union"
	default:
		return "Unknown"
	}
}

func intKindLabel(k cambium.IntKind) string {
	switch k {
	case cambium.IntKindI8:
		return "Int8"
	case cambium.IntKindI16:
		return "Int16"
	case cambium.IntKindI32:
		return "Int32"
	case cambium.IntKindI64:
		return "Int64"
	case cambium.IntKindU8:
		return "Uint8"
	case cambium.IntKindU16:
		return "Uint16"
	case cambium.IntKindU32:
		return "Uint32"
	case cambium.IntKindU64:
		return "Uint64"
	default:
		return "Int"
	}
}

func safeFieldIdent(name string, used map[string]bool) string {
	ident := toPascalCase(name)
	if ident == "" {
		ident = "Field"
	}
	if first := []rune(ident)[0]; first >= '0' && first <= '9' {
		ident = "Field" + ident
	}
	if isGoKeyword(name) || isGeneratedFieldReservedIdent(ident) {
		ident += "_"
	}
	base := ident
	suffix := 2
	for used[ident] {
		ident = fmt.Sprintf("%s%d", base, suffix)
		suffix++
	}
	used[ident] = true
	return ident
}

func safeTypeIdent(name string, used map[string]bool) string {
	ident := toPascalCase(name)
	if ident == "" {
		ident = "Node"
	}
	if first := []rune(ident)[0]; first >= '0' && first <= '9' {
		ident = "Node" + ident
	}
	base := ident
	suffix := 2
	for used[ident] {
		ident = fmt.Sprintf("%s%d", base, suffix)
		suffix++
	}
	used[ident] = true
	return ident
}

func isGeneratedFieldReservedIdent(ident string) bool {
	switch ident {
	case "CambiumMetadata", "ToXML", "ToJSONIETF", "Validate":
		return true
	default:
		return false
	}
}

func isGoKeyword(name string) bool {
	switch name {
	case "break", "default", "func", "interface", "select", "case", "defer", "go",
		"map", "struct", "chan", "else", "goto", "package", "switch", "const",
		"fallthrough", "if", "range", "type", "continue", "for", "import",
		"return", "var":
		return true
	default:
		return false
	}
}

func safeVariantIdent(name string, used map[string]bool) string {
	ident := toPascalCase(name)
	if ident == "" {
		ident = "Value"
	}
	if first := []rune(ident)[0]; first >= '0' && first <= '9' {
		ident = "Value" + ident
	}
	if ident == "Iota" {
		ident += "_"
	}
	base := ident
	suffix := 2
	for used[ident] {
		ident = fmt.Sprintf("%s%d", base, suffix)
		suffix++
	}
	used[ident] = true
	return ident
}

func toPascalCase(s string) string {
	out := strings.Builder{}
	upper := true
	for _, c := range s {
		switch c {
		case '-', '_', '.':
			upper = true
		default:
			if upper {
				out.WriteRune(toUpper(c))
				upper = false
			} else {
				out.WriteRune(c)
			}
		}
	}
	if out.Len() == 0 {
		out.WriteString("Node")
	}
	return out.String()
}

func toUpper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return r - 'a' + 'A'
	}
	return r
}

func jsonIntegerKindQuoted(kind cambium.IntKind) bool {
	return kind == cambium.IntKindI64 || kind == cambium.IntKindU64
}

func goTypeForIntKind(k cambium.IntKind) string {
	switch k {
	case cambium.IntKindI8:
		return "int8"
	case cambium.IntKindI16:
		return "int16"
	case cambium.IntKindI32:
		return "int32"
	case cambium.IntKindI64:
		return "int64"
	case cambium.IntKindU8:
		return "uint8"
	case cambium.IntKindU16:
		return "uint16"
	case cambium.IntKindU32:
		return "uint32"
	case cambium.IntKindU64:
		return "uint64"
	default:
		return "int64"
	}
}

func isSignedIntKind(k cambium.IntKind) bool {
	switch k {
	case cambium.IntKindI8, cambium.IntKindI16, cambium.IntKindI32, cambium.IntKindI64:
		return true
	default:
		return false
	}
}

type intLimits struct {
	min string
	max string
}

func intTypeLimits(k cambium.IntKind) intLimits {
	switch k {
	case cambium.IntKindI8:
		return intLimits{min: "-128", max: "127"}
	case cambium.IntKindI16:
		return intLimits{min: "-32768", max: "32767"}
	case cambium.IntKindI32:
		return intLimits{min: "-2147483648", max: "2147483647"}
	case cambium.IntKindI64:
		return intLimits{min: "-9223372036854775808", max: "9223372036854775807"}
	case cambium.IntKindU8:
		return intLimits{min: "0", max: "255"}
	case cambium.IntKindU16:
		return intLimits{min: "0", max: "65535"}
	case cambium.IntKindU32:
		return intLimits{min: "0", max: "4294967295"}
	case cambium.IntKindU64:
		return intLimits{min: "0", max: "18446744073709551615"}
	default:
		return intLimits{min: "-9223372036854775808", max: "9223372036854775807"}
	}
}

func parseIntBound(s string, limits intLimits) int64 {
	if s == "min" {
		v, _ := strconv.ParseInt(limits.min, 10, 64)
		return v
	}
	if s == "max" {
		v, _ := strconv.ParseInt(limits.max, 10, 64)
		return v
	}
	v, _ := strconv.ParseInt(s, 10, 64)
	return v
}

func parseLengthBound(s string) int64 {
	if s == "min" {
		return 0
	}
	if s == "max" {
		return int64(^uint(0) >> 1)
	}
	v, _ := strconv.ParseInt(s, 10, 64)
	return v
}
